<?php

namespace DavideCasiraghi\LaravelEventsCalendar\Tests;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/*
|--------------------------------------------------------------------------
| Seeders
|--------------------------------------------------------------------------
|
| Seders are used to generate datas to populate the database of the test environment.
|
*/

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries = [
          ['id' => '1', 'name' => 'Italy', 'continent_id' => '6', 'code' => 'IT', 'timezone' => '+2:00'],
          ['id' => '2', 'name' => 'United States', 'continent_id' => '3', 'code' => 'US', 'timezone' => '+2:00'],
          ['id' => '3', 'name' => 'Algeria', 'continent_id' => '1', 'code' => 'DZ', 'timezone' => '+2:00'],
          ['id' => '4', 'name' => 'Wallis and Futuna', 'continent_id' => '4', 'code' => 'WF', 'timezone' => '+2:00'],
          ['id' => '5', 'name' => 'Angola', 'continent_id' => '1', 'code' => 'AO', 'timezone' => '+2:00'],
          ['id' => '6', 'name' => 'Benin', 'continent_id' => '1', 'code' => 'BJ', 'timezone' => '+2:00'],
          ['id' => '7', 'name' => 'Botswana', 'continent_id' => '1', 'code' => 'BW', 'timezone' => '+2:00'],
          ['id' => '8', 'name' => 'Burkina Faso', 'continent_id' => '1', 'code' => 'BF', 'timezone' => '+2:00'],
          ['id' => '9', 'name' => 'Burundi', 'continent_id' => '1', 'code' => 'BI', 'timezone' => '+2:00'],
          ['id' => '10', 'name' => 'Cameroon', 'continent_id' => '1', 'code' => 'CM', 'timezone' => '+2:00'],
          ['id' => '11', 'name' => 'Cape Verde', 'continent_id' => '1', 'code' => 'CV', 'timezone' => '+2:00'],
          ['id' => '12', 'name' => 'Central African Republic', 'continent_id' => '1', 'code' => 'CF', 'timezone' => '+2:00'],
          ['id' => '13', 'name' => 'Chad', 'continent_id' => '1', 'code' => 'TD', 'timezone' => '+2:00'],
          ['id' => '14', 'name' => 'Comoros', 'continent_id' => '1', 'code' => 'KM', 'timezone' => '+2:00'],
          ['id' => '15', 'name' => 'Congo - Brazzaville', 'continent_id' => '1', 'code' => 'CG', 'timezone' => '+2:00'],
          ['id' => '16', 'name' => 'Congo - Kinshasa', 'continent_id' => '1', 'code' => 'CD', 'timezone' => '+2:00'],
          ['id' => '17', 'name' => 'Cote d\'Ivoire', 'continent_id' => '1', 'code' => 'CI', 'timezone' => '+2:00'],
          ['id' => '18', 'name' => 'Djibouti', 'continent_id' => '1', 'code' => 'DJ', 'timezone' => '+2:00'],
          ['id' => '19', 'name' => 'Egypt', 'continent_id' => '1', 'code' => 'EG', 'timezone' => '+2:00'],
          ['id' => '20', 'name' => 'Equatorial Guinea', 'continent_id' => '1', 'code' => 'GQ', 'timezone' => '+2:00'],
          ['id' => '21', 'name' => 'Eritrea', 'continent_id' => '1', 'code' => 'ER', 'timezone' => '+2:00'],
          ['id' => '22', 'name' => 'Ethiopia', 'continent_id' => '1', 'code' => 'ET', 'timezone' => '+2:00'],
          ['id' => '23', 'name' => 'Gabon', 'continent_id' => '1', 'code' => 'GA', 'timezone' => '+2:00'],
          ['id' => '24', 'name' => 'Gambia', 'continent_id' => '1', 'code' => 'GM', 'timezone' => '+2:00'],
          ['id' => '25', 'name' => 'Ghana', 'continent_id' => '1', 'code' => 'GH', 'timezone' => '+2:00'],
          ['id' => '26', 'name' => 'Guinea', 'continent_id' => '1', 'code' => 'GN', 'timezone' => '+2:00'],
          ['id' => '27', 'name' => 'Guinea Bissau', 'continent_id' => '1', 'code' => 'GW', 'timezone' => '+2:00'],
          ['id' => '28', 'name' => 'Kenya', 'continent_id' => '1', 'code' => 'KE', 'timezone' => '+2:00'],
          ['id' => '29', 'name' => 'Lesotho', 'continent_id' => '1', 'code' => 'LS', 'timezone' => '+2:00'],
          ['id' => '30', 'name' => 'Liberia', 'continent_id' => '1', 'code' => 'LR', 'timezone' => '+2:00'],
          ['id' => '31', 'name' => 'Libya', 'continent_id' => '1', 'code' => 'LY', 'timezone' => '+2:00'],
          ['id' => '32', 'name' => 'Madagascar', 'continent_id' => '1', 'code' => 'MG', 'timezone' => '+2:00'],
          ['id' => '33', 'name' => 'Malawi', 'continent_id' => '1', 'code' => 'MW', 'timezone' => '+2:00'],
          ['id' => '34', 'name' => 'Mali', 'continent_id' => '1', 'code' => 'ML', 'timezone' => '+2:00'],
          ['id' => '35', 'name' => 'Mauritania', 'continent_id' => '1', 'code' => 'MR', 'timezone' => '+2:00'],
          ['id' => '36', 'name' => 'Mauritius', 'continent_id' => '1', 'code' => 'MU', 'timezone' => '+2:00'],
          ['id' => '37', 'name' => 'Mayotte', 'continent_id' => '1', 'code' => 'YT', 'timezone' => '+2:00'],
          ['id' => '38', 'name' => 'Morocco', 'continent_id' => '1', 'code' => 'MA', 'timezone' => '+2:00'],
          ['id' => '39', 'name' => 'Mozambique', 'continent_id' => '1', 'code' => 'MZ', 'timezone' => '+2:00'],
          ['id' => '40', 'name' => 'Namibia', 'continent_id' => '1', 'code' => 'NA', 'timezone' => '+2:00'],
          ['id' => '41', 'name' => 'Niger', 'continent_id' => '1', 'code' => 'NE', 'timezone' => '+2:00'],
          ['id' => '42', 'name' => 'Vanuatu', 'continent_id' => '4', 'code' => 'VU', 'timezone' => '+2:00'],
          ['id' => '43', 'name' => 'Rwanda', 'continent_id' => '1', 'code' => 'RW', 'timezone' => '+2:00'],
          ['id' => '44', 'name' => 'Reunion', 'continent_id' => '1', 'code' => 'RE', 'timezone' => '+2:00'],
          ['id' => '45', 'name' => 'Saint Helena', 'continent_id' => '1', 'code' => 'SH', 'timezone' => '+2:00'],
          ['id' => '46', 'name' => 'Senegal', 'continent_id' => '1', 'code' => 'SN', 'timezone' => '+2:00'],
          ['id' => '47', 'name' => 'Seychelles', 'continent_id' => '1', 'code' => 'SC', 'timezone' => '+2:00'],
          ['id' => '48', 'name' => 'Sierra Leone', 'continent_id' => '1', 'code' => 'SL', 'timezone' => '+2:00'],
          ['id' => '49', 'name' => 'Somalia', 'continent_id' => '1', 'code' => 'SO', 'timezone' => '+2:00'],
          ['id' => '50', 'name' => 'South Africa', 'continent_id' => '1', 'code' => 'ZA', 'timezone' => '+2:00'],
          ['id' => '51', 'name' => 'Sudan', 'continent_id' => '1', 'code' => 'SD', 'timezone' => '+2:00'],
          ['id' => '52', 'name' => 'Swaziland', 'continent_id' => '1', 'code' => 'SZ', 'timezone' => '+2:00'],
          ['id' => '53', 'name' => 'Sao Tome and Príncipe', 'continent_id' => '1', 'code' => 'ST', 'timezone' => '+2:00'],
          ['id' => '54', 'name' => 'Tanzania', 'continent_id' => '1', 'code' => 'TZ', 'timezone' => '+2:00'],
          ['id' => '55', 'name' => 'Togo', 'continent_id' => '1', 'code' => 'TG', 'timezone' => '+2:00'],
          ['id' => '56', 'name' => 'Tunisia', 'continent_id' => '1', 'code' => 'TN', 'timezone' => '+2:00'],
          ['id' => '57', 'name' => 'Uganda', 'continent_id' => '1', 'code' => 'UG', 'timezone' => '+2:00'],
          ['id' => '58', 'name' => 'U.S. Minor Outlying Islands', 'continent_id' => '4', 'code' => 'UM', 'timezone' => '+2:00'],
          ['id' => '59', 'name' => 'Tuvalu', 'continent_id' => '4', 'code' => 'TV', 'timezone' => '+2:00'],
          ['id' => '60', 'name' => 'Western Sahara', 'continent_id' => '1', 'code' => 'EH', 'timezone' => '+2:00'],
          ['id' => '61', 'name' => 'Zambia', 'continent_id' => '1', 'code' => 'ZM', 'timezone' => '+2:00'],
          ['id' => '62', 'name' => 'Zimbabwe', 'continent_id' => '1', 'code' => 'ZW', 'timezone' => '+2:00'],
          ['id' => '63', 'name' => 'Anguilla', 'continent_id' => '3', 'code' => 'AI', 'timezone' => '+2:00'],
          ['id' => '64', 'name' => 'Antigua and Barbuda', 'continent_id' => '3', 'code' => 'AG', 'timezone' => '+2:00'],
          ['id' => '65', 'name' => 'Argentina', 'continent_id' => '7', 'code' => 'AR', 'timezone' => '+2:00'],
          ['id' => '66', 'name' => 'Aruba', 'continent_id' => '7', 'code' => 'AW', 'timezone' => '+2:00'],
          ['id' => '67', 'name' => 'Bahamas', 'continent_id' => '3', 'code' => 'BS', 'timezone' => '+2:00'],
          ['id' => '68', 'name' => 'Barbados', 'continent_id' => '7', 'code' => 'BB', 'timezone' => '+2:00'],
          ['id' => '69', 'name' => 'Belize', 'continent_id' => '3', 'code' => 'BZ', 'timezone' => '+2:00'],
          ['id' => '70', 'name' => 'Bermuda', 'continent_id' => '3', 'code' => 'BM', 'timezone' => '+2:00'],
          ['id' => '71', 'name' => 'Bolivia', 'continent_id' => '7', 'code' => 'BO', 'timezone' => '+2:00'],
          ['id' => '72', 'name' => 'Brazil', 'continent_id' => '7', 'code' => 'BR', 'timezone' => '+2:00'],
          ['id' => '73', 'name' => 'British Virgin Islands', 'continent_id' => '3', 'code' => 'VG', 'timezone' => '+2:00'],
          ['id' => '74', 'name' => 'Canada', 'continent_id' => '3', 'code' => 'CA', 'timezone' => '+2:00'],
          ['id' => '75', 'name' => 'Cayman Islands', 'continent_id' => '3', 'code' => 'KY', 'timezone' => '+2:00'],
          ['id' => '76', 'name' => 'Chile', 'continent_id' => '7', 'code' => 'CL', 'timezone' => '+2:00'],
          ['id' => '77', 'name' => 'Colombia', 'continent_id' => '7', 'code' => 'CO', 'timezone' => '+2:00'],
          ['id' => '78', 'name' => 'Costa Rica', 'continent_id' => '3', 'code' => 'CR', 'timezone' => '+2:00'],
          ['id' => '79', 'name' => 'Cuba', 'continent_id' => '3', 'code' => 'CU', 'timezone' => '+2:00'],
          ['id' => '80', 'name' => 'Dominica', 'continent_id' => '3', 'code' => 'DM', 'timezone' => '+2:00'],
          ['id' => '81', 'name' => 'Dominican Republic', 'continent_id' => '3', 'code' => 'DO', 'timezone' => '+2:00'],
          ['id' => '82', 'name' => 'Ecuador', 'continent_id' => '7', 'code' => 'EC', 'timezone' => '+2:00'],
          ['id' => '83', 'name' => 'El Salvador', 'continent_id' => '3', 'code' => 'SV', 'timezone' => '+2:00'],
          ['id' => '84', 'name' => 'Falkland Islands', 'continent_id' => '7', 'code' => 'FK', 'timezone' => '+2:00'],
          ['id' => '85', 'name' => 'French Guiana', 'continent_id' => '7', 'code' => 'GF', 'timezone' => '+2:00'],
          ['id' => '86', 'name' => 'Greenland', 'continent_id' => '3', 'code' => 'GL', 'timezone' => '+2:00'],
          ['id' => '87', 'name' => 'Grenada', 'continent_id' => '3', 'code' => 'GD', 'timezone' => '+2:00'],
          ['id' => '88', 'name' => 'Guadeloupe', 'continent_id' => '3', 'code' => 'GP', 'timezone' => '+2:00'],
          ['id' => '89', 'name' => 'Guatemala', 'continent_id' => '3', 'code' => 'GT'],
          ['id' => '90', 'name' => 'Guyana', 'continent_id' => '7', 'code' => 'GY', 'timezone' => '+2:00'],
          ['id' => '91', 'name' => 'Haiti', 'continent_id' => '3', 'code' => 'HT', 'timezone' => '+2:00'],
          ['id' => '92', 'name' => 'Honduras', 'continent_id' => '3', 'code' => 'HN', 'timezone' => '+2:00'],
          ['id' => '93', 'name' => 'Jamaica', 'continent_id' => '3', 'code' => 'JM', 'timezone' => '+2:00'],
          ['id' => '94', 'name' => 'Martinique', 'continent_id' => '3', 'code' => 'MQ', 'timezone' => '+2:00'],
          ['id' => '95', 'name' => 'Mexico', 'continent_id' => '7', 'code' => 'MX', 'timezone' => '+2:00'],
          ['id' => '96', 'name' => 'Montserrat', 'continent_id' => '3', 'code' => 'MS', 'timezone' => '+2:00'],
          ['id' => '97', 'name' => 'Netherlands Antilles', 'continent_id' => '7', 'code' => 'AN', 'timezone' => '+2:00'],
          ['id' => '98', 'name' => 'Nicaragua', 'continent_id' => '3', 'code' => 'NI', 'timezone' => '+2:00'],
          ['id' => '99', 'name' => 'Panama', 'continent_id' => '3', 'code' => 'PA', 'timezone' => '+2:00'],
          ['id' => '100', 'name' => 'Paraguay', 'continent_id' => '7', 'code' => 'PY', 'timezone' => '+2:00'],
          ['id' => '101', 'name' => 'Peru', 'continent_id' => '7', 'code' => 'PE', 'timezone' => '+2:00'],
          ['id' => '102', 'name' => 'Puerto Rico', 'continent_id' => '3', 'code' => 'PR', 'timezone' => '+2:00'],
          ['id' => '103', 'name' => 'Saint Barthelemy', 'continent_id' => '3', 'code' => 'BL', 'timezone' => '+2:00'],
          ['id' => '104', 'name' => 'Saint Kitts and Nevis', 'continent_id' => '3', 'code' => 'KL', 'timezone' => '+2:00'],
          ['id' => '105', 'name' => 'Saint Lucia', 'continent_id' => '3', 'code' => 'LC', 'timezone' => '+2:00'],
          ['id' => '106', 'name' => 'Saint Martin', 'continent_id' => '3', 'code' => 'MF', 'timezone' => '+2:00'],
          ['id' => '107', 'name' => 'Saint Pierre and Miquelon', 'continent_id' => '3', 'code' => 'PM', 'timezone' => '+2:00'],
          ['id' => '108', 'name' => 'Saint Vincent and the Grenadines', 'continent_id' => '3', 'code' => 'VC', 'timezone' => '+2:00'],
          ['id' => '109', 'name' => 'Suriname', 'continent_id' => '7', 'code' => 'SR', 'timezone' => '+2:00'],
          ['id' => '110', 'name' => 'Trinidad and Tobago', 'continent_id' => '7', 'code' => 'TT', 'timezone' => '+2:00'],
          ['id' => '111', 'name' => 'Turks and Caicos Islands', 'continent_id' => '3', 'code' => 'TC', 'timezone' => '+2:00'],
          ['id' => '112', 'name' => 'U.S. Virgin Islands', 'continent_id' => '3', 'code' => 'VI', 'timezone' => '+2:00'],
          ['id' => '113', 'name' => 'Tonga', 'continent_id' => '4', 'code' => 'TO', 'timezone' => '+2:00'],
          ['id' => '114', 'name' => 'Uruguay', 'continent_id' => '7', 'code' => 'UY', 'timezone' => '+2:00'],
          ['id' => '115', 'name' => 'Venezuela', 'continent_id' => '7', 'code' => 'VE', 'timezone' => '+2:00'],
          ['id' => '116', 'name' => 'Tokelau', 'continent_id' => '4', 'code' => 'TK', 'timezone' => '+2:00'],
          ['id' => '117', 'name' => 'Afghanistan', 'continent_id' => '5', 'code' => 'AF', 'timezone' => '+2:00'],
          ['id' => '118', 'name' => 'Armenia', 'continent_id' => '5', 'code' => 'AM', 'timezone' => '+2:00'],
          ['id' => '119', 'name' => 'Azerbaijan', 'continent_id' => '5', 'code' => 'AZ', 'timezone' => '+2:00'],
          ['id' => '120', 'name' => 'Bahrain', 'continent_id' => '5', 'code' => 'BH'],
          ['id' => '121', 'name' => 'Bangladesh', 'continent_id' => '5', 'code' => 'BD', 'timezone' => '+2:00'],
          ['id' => '122', 'name' => 'Bhutan', 'continent_id' => '5', 'code' => 'BT', 'timezone' => '+2:00'],
          ['id' => '123', 'name' => 'Brunei', 'continent_id' => '5', 'code' => 'BN', 'timezone' => '+2:00'],
          ['id' => '124', 'name' => 'Cambodia', 'continent_id' => '5', 'code' => 'KH', 'timezone' => '+2:00'],
          ['id' => '125', 'name' => 'China', 'continent_id' => '5', 'code' => 'CN', 'timezone' => '+2:00'],
          ['id' => '126', 'name' => 'Cyprus', 'continent_id' => '5', 'code' => 'CY', 'timezone' => '+2:00'],
          ['id' => '127', 'name' => 'Georgia', 'continent_id' => '5', 'code' => 'GE', 'timezone' => '+2:00'],
          ['id' => '129', 'name' => 'Hong Kong SAR China', 'continent_id' => '5', 'code' => 'HK', 'timezone' => '+2:00'],
          ['id' => '130', 'name' => 'India', 'continent_id' => '5', 'code' => 'IN', 'timezone' => '+2:00'],
          ['id' => '131', 'name' => 'Indonesia', 'continent_id' => '5', 'code' => 'ID', 'timezone' => '+2:00'],
          ['id' => '132', 'name' => 'Iran', 'continent_id' => '5', 'code' => 'IR', 'timezone' => '+2:00'],
          ['id' => '133', 'name' => 'Iraq', 'continent_id' => '5', 'code' => 'IQ', 'timezone' => '+2:00'],
          ['id' => '134', 'name' => 'Israel', 'continent_id' => '5', 'code' => 'IL', 'timezone' => '+2:00'],
          ['id' => '135', 'name' => 'Japan', 'continent_id' => '5', 'code' => 'JP', 'timezone' => '+2:00'],
          ['id' => '136', 'name' => 'Jordan', 'continent_id' => '5', 'code' => 'JO', 'timezone' => '+2:00'],
          ['id' => '137', 'name' => 'Kazakhstan', 'continent_id' => '5', 'code' => 'KZ', 'timezone' => '+2:00'],
          ['id' => '138', 'name' => 'Kuwait', 'continent_id' => '5', 'code' => 'KW', 'timezone' => '+2:00'],
          ['id' => '139', 'name' => 'Kyrgyzstan', 'continent_id' => '5', 'code' => 'KG', 'timezone' => '+2:00'],
          ['id' => '140', 'name' => 'Laos', 'continent_id' => '5', 'code' => 'LA', 'timezone' => '+2:00'],
          ['id' => '141', 'name' => 'Lebanon', 'continent_id' => '5', 'code' => 'LB', 'timezone' => '+2:00'],
          ['id' => '142', 'name' => 'Macau SAR China', 'continent_id' => '5', 'code' => 'MO', 'timezone' => '+2:00'],
          ['id' => '143', 'name' => 'Malaysia', 'continent_id' => '5', 'code' => 'MY', 'timezone' => '+2:00'],
          ['id' => '144', 'name' => 'Maldives', 'continent_id' => '5', 'code' => 'MV', 'timezone' => '+2:00'],
          ['id' => '145', 'name' => 'Mongolia', 'continent_id' => '5', 'code' => 'MN', 'timezone' => '+2:00'],
          ['id' => '146', 'name' => 'Myanmar Burma', 'continent_id' => '5', 'code' => 'MM', 'timezone' => '+2:00'],
          ['id' => '147', 'name' => 'Nepal', 'continent_id' => '5', 'code' => 'NP', 'timezone' => '+2:00'],
          ['id' => '148', 'name' => 'Neutral Zone', 'continent_id' => '5', 'code' => 'NT', 'timezone' => '+2:00'],
          ['id' => '149', 'name' => 'North Korea', 'continent_id' => '5', 'code' => 'KP', 'timezone' => '+2:00'],
          ['id' => '150', 'name' => 'Oman', 'continent_id' => '5', 'code' => 'OM', 'timezone' => '+2:00'],
          ['id' => '151', 'name' => 'Pakistan', 'continent_id' => '5', 'code' => 'PK', 'timezone' => '+2:00'],
          ['id' => '152', 'name' => 'Palestinian Territories', 'continent_id' => '5', 'code' => 'PS', 'timezone' => '+2:00'],
          ['id' => '153', 'name' => 'People s Democratic Republic of Yemen', 'continent_id' => '5', 'code' => 'YD', 'timezone' => '+2:00'],
          ['id' => '154', 'name' => 'Philippines', 'continent_id' => '5', 'code' => 'PH', 'timezone' => '+2:00'],
          ['id' => '155', 'name' => 'Qatar', 'continent_id' => '5', 'code' => 'QA', 'timezone' => '+2:00'],
          ['id' => '156', 'name' => 'Saudi Arabia', 'continent_id' => '5', 'code' => 'SA', 'timezone' => '+2:00'],
          ['id' => '157', 'name' => 'Singapore', 'continent_id' => '5', 'code' => 'SG', 'timezone' => '+2:00'],
          ['id' => '158', 'name' => 'South Korea', 'continent_id' => '5', 'code' => 'KR', 'timezone' => '+2:00'],
          ['id' => '159', 'name' => 'Sri Lanka', 'continent_id' => '5', 'code' => 'LK', 'timezone' => '+2:00'],
          ['id' => '160', 'name' => 'Syria', 'continent_id' => '5', 'code' => 'SY', 'timezone' => '+2:00'],
          ['id' => '161', 'name' => 'Taiwan', 'continent_id' => '5', 'code' => 'TW', 'timezone' => '+2:00'],
          ['id' => '162', 'name' => 'Tajikistan', 'continent_id' => '5', 'code' => 'TJ', 'timezone' => '+2:00'],
          ['id' => '163', 'name' => 'Thailand', 'continent_id' => '5', 'code' => 'TH', 'timezone' => '+2:00'],
          ['id' => '164', 'name' => 'Timor Leste', 'continent_id' => '5', 'code' => 'TL', 'timezone' => '+2:00'],
          ['id' => '165', 'name' => 'Turkey', 'continent_id' => '5', 'code' => 'TR', 'timezone' => '+2:00'],
          ['id' => '166', 'name' => 'Turkmenistan', 'continent_id' => '5', 'code' => 'TM', 'timezone' => '+2:00'],
          ['id' => '167', 'name' => 'United Arab Emirates', 'continent_id' => '5', 'code' => 'AE', 'timezone' => '+2:00'],
          ['id' => '168', 'name' => 'Uzbekistan', 'continent_id' => '5', 'code' => 'UZ', 'timezone' => '+2:00'],
          ['id' => '169', 'name' => 'Vietnam', 'continent_id' => '5', 'code' => 'VN', 'timezone' => '+2:00'],
          ['id' => '170', 'name' => 'Yemen', 'continent_id' => '5', 'code' => 'YE', 'timezone' => '+2:00'],
          ['id' => '171', 'name' => 'Albania', 'continent_id' => '6', 'code' => 'AL', 'timezone' => '+2:00'],
          ['id' => '172', 'name' => 'Andorra', 'continent_id' => '6', 'code' => 'AD', 'timezone' => '+2:00'],
          ['id' => '173', 'name' => 'Austria', 'continent_id' => '6', 'code' => 'AT', 'timezone' => '+2:00'],
          ['id' => '174', 'name' => 'Belarus', 'continent_id' => '6', 'code' => 'BY', 'timezone' => '+2:00'],
          ['id' => '175', 'name' => 'Belgium', 'continent_id' => '6', 'code' => 'BE', 'timezone' => '+2:00'],
          ['id' => '176', 'name' => 'Bosnia and Herzegovina', 'continent_id' => '6', 'code' => 'BA', 'timezone' => '+2:00'],
          ['id' => '177', 'name' => 'Bulgaria', 'continent_id' => '6', 'code' => 'BG', 'timezone' => '+2:00'],
          ['id' => '178', 'name' => 'Croatia', 'continent_id' => '6', 'code' => 'HR', 'timezone' => '+2:00'],
          ['id' => '179', 'name' => 'South Georgia and the South Sandwich Isl', 'continent_id' => '4', 'code' => 'GS', 'timezone' => '+2:00'],
          ['id' => '180', 'name' => 'Czech Republic', 'continent_id' => '6', 'code' => 'CZ', 'timezone' => '+2:00'],
          ['id' => '181', 'name' => 'Denmark', 'continent_id' => '6', 'code' => 'DK', 'timezone' => '+2:00'],
          ['id' => '182', 'name' => 'Estonia', 'continent_id' => '6', 'code' => 'EE', 'timezone' => '+2:00'],
          ['id' => '183', 'name' => 'Faroe Islands', 'continent_id' => '6', 'code' => 'FO', 'timezone' => '+2:00'],
          ['id' => '184', 'name' => 'Finland', 'continent_id' => '6', 'code' => 'FI', 'timezone' => '+2:00'],
          ['id' => '185', 'name' => 'France', 'continent_id' => '6', 'code' => 'FR', 'timezone' => '+2:00'],
          ['id' => '186', 'name' => 'Germany', 'continent_id' => '6', 'code' => 'DE', 'timezone' => '+2:00'],
          ['id' => '187', 'name' => 'Gibraltar', 'continent_id' => '6', 'code' => 'GI', 'timezone' => '+2:00'],
          ['id' => '188', 'name' => 'Greece', 'continent_id' => '6', 'code' => 'GR', 'timezone' => '+2:00'],
          ['id' => '189', 'name' => 'Guernsey', 'continent_id' => '6', 'code' => 'GG', 'timezone' => '+2:00'],
          ['id' => '190', 'name' => 'Hungary', 'continent_id' => '6', 'code' => 'HU', 'timezone' => '+2:00'],
          ['id' => '191', 'name' => 'Iceland', 'continent_id' => '6', 'code' => 'IS', 'timezone' => '+2:00'],
          ['id' => '192', 'name' => 'Ireland', 'continent_id' => '6', 'code' => 'IE', 'timezone' => '+2:00'],
          ['id' => '193', 'name' => 'Isle of Man', 'continent_id' => '6', 'code' => 'IM', 'timezone' => '+2:00'],
          ['id' => '195', 'name' => 'Jersey', 'continent_id' => '6', 'code' => 'JE', 'timezone' => '+2:00'],
          ['id' => '196', 'name' => 'Latvia', 'continent_id' => '6', 'code' => 'LV', 'timezone' => '+2:00'],
          ['id' => '197', 'name' => 'Liechtenstein', 'continent_id' => '6', 'code' => 'LI', 'timezone' => '+2:00'],
          ['id' => '198', 'name' => 'Lithuania', 'continent_id' => '6', 'code' => 'LT', 'timezone' => '+2:00'],
          ['id' => '199', 'name' => 'Luxembourg', 'continent_id' => '6', 'code' => 'LU', 'timezone' => '+2:00'],
          ['id' => '200', 'name' => 'Macedonia', 'continent_id' => '6', 'code' => 'MK', 'timezone' => '+2:00'],
          ['id' => '201', 'name' => 'Malta', 'continent_id' => '6', 'code' => 'MT', 'timezone' => '+2:00'],
          ['id' => '202', 'name' => 'Metropolitan France', 'continent_id' => '6', 'code' => 'FX', 'timezone' => '+2:00'],
          ['id' => '203', 'name' => 'Moldova', 'continent_id' => '6', 'code' => 'MD', 'timezone' => '+2:00'],
          ['id' => '204', 'name' => 'Monaco', 'continent_id' => '6', 'code' => 'MC', 'timezone' => '+2:00'],
          ['id' => '205', 'name' => 'Montenegro', 'continent_id' => '6', 'code' => 'ME', 'timezone' => '+2:00'],
          ['id' => '206', 'name' => 'Netherlands', 'continent_id' => '6', 'code' => 'NL', 'timezone' => '+2:00'],
          ['id' => '207', 'name' => 'Norway', 'continent_id' => '6', 'code' => 'NO', 'timezone' => '+2:00'],
          ['id' => '208', 'name' => 'Poland', 'continent_id' => '6', 'code' => 'PL', 'timezone' => '+2:00'],
          ['id' => '209', 'name' => 'Portugal', 'continent_id' => '6', 'code' => 'PT', 'timezone' => '+2:00'],
          ['id' => '210', 'name' => 'Romania', 'continent_id' => '6', 'code' => 'RO', 'timezone' => '+2:00'],
          ['id' => '211', 'name' => 'Russia', 'continent_id' => '6', 'code' => 'RU', 'timezone' => '+2:00'],
          ['id' => '212', 'name' => 'San Marino', 'continent_id' => '6', 'code' => 'SM', 'timezone' => '+2:00'],
          ['id' => '213', 'name' => 'Serbia', 'continent_id' => '6', 'code' => 'RS', 'timezone' => '+2:00'],
          ['id' => '214', 'name' => 'Serbia and Montenegro', 'continent_id' => '6', 'code' => 'CS', 'timezone' => '+2:00'],
          ['id' => '215', 'name' => 'Slovakia', 'continent_id' => '6', 'code' => 'SK', 'timezone' => '+2:00'],
          ['id' => '216', 'name' => 'Slovenia', 'continent_id' => '6', 'code' => 'SI', 'timezone' => '+2:00'],
          ['id' => '217', 'name' => 'Spain', 'continent_id' => '6', 'code' => 'ES', 'timezone' => '+2:00'],
          ['id' => '218', 'name' => 'Svalbard and Jan Mayen', 'continent_id' => '6', 'code' => 'SJ', 'timezone' => '+2:00'],
          ['id' => '219', 'name' => 'Sweden', 'continent_id' => '6', 'code' => 'SE', 'timezone' => '+2:00'],
          ['id' => '220', 'name' => 'Switzerland', 'continent_id' => '6', 'code' => 'CH', 'timezone' => '+2:00'],
          ['id' => '221', 'name' => 'Ukraine', 'continent_id' => '6', 'code' => 'UA', 'timezone' => '+2:00'],
          ['id' => '222', 'name' => 'Union of Soviet Socialist Republics', 'continent_id' => '6', 'code' => 'SU', 'timezone' => '+2:00'],
          ['id' => '223', 'name' => 'United Kingdom', 'continent_id' => '6', 'code' => 'GB', 'timezone' => '+2:00'],
          ['id' => '224', 'name' => 'Vatican City', 'continent_id' => '6', 'code' => 'VA', 'timezone' => '+2:00'],
          ['id' => '225', 'name' => 'Aland Islands', 'continent_id' => '6', 'code' => 'AX', 'timezone' => '+2:00'],
          ['id' => '226', 'name' => 'American Samoa', 'continent_id' => '4', 'code' => 'AS', 'timezone' => '+2:00'],
          ['id' => '227', 'name' => 'Antarctica', 'continent_id' => '4', 'code' => 'AQ', 'timezone' => '+2:00'],
          ['id' => '228', 'name' => 'Australia', 'continent_id' => '4', 'code' => 'AU', 'timezone' => '+2:00'],
          ['id' => '229', 'name' => 'Bouvet Island', 'continent_id' => '4', 'code' => 'BV', 'timezone' => '+2:00'],
          ['id' => '230', 'name' => 'British Indian Ocean Territory', 'continent_id' => '4', 'code' => 'IO', 'timezone' => '+2:00'],
          ['id' => '231', 'name' => 'Christmas Island', 'continent_id' => '4', 'code' => 'CX', 'timezone' => '+2:00'],
          ['id' => '232', 'name' => 'Cocos Keeling Islands', 'continent_id' => '4', 'code' => 'CC', 'timezone' => '+2:00'],
          ['id' => '234', 'name' => 'Cook Islands', 'continent_id' => '4', 'code' => 'CK', 'timezone' => '+2:00'],
          ['id' => '235', 'name' => 'Fiji', 'continent_id' => '4', 'code' => 'FJ', 'timezone' => '+2:00'],
          ['id' => '236', 'name' => 'French Polynesia', 'continent_id' => '4', 'code' => 'PF', 'timezone' => '+2:00'],
          ['id' => '237', 'name' => 'French Southern Territories', 'continent_id' => '4', 'code' => 'TF', 'timezone' => '+2:00'],
          ['id' => '238', 'name' => 'Guam', 'continent_id' => '4', 'code' => 'GU', 'timezone' => '+2:00'],
          ['id' => '239', 'name' => 'Heard Island and McDonald Islands', 'continent_id' => '4', 'code' => 'HM', 'timezone' => '+2:00'],
          ['id' => '240', 'name' => 'Kiribati', 'continent_id' => '4', 'code' => 'KI', 'timezone' => '+2:00'],
          ['id' => '241', 'name' => 'Marshall Islands', 'continent_id' => '4', 'code' => 'MH', 'timezone' => '+2:00'],
          ['id' => '242', 'name' => 'Micronesia', 'continent_id' => '4', 'code' => 'FM', 'timezone' => '+2:00'],
          ['id' => '243', 'name' => 'Nauru', 'continent_id' => '4', 'code' => 'NR', 'timezone' => '+2:00'],
          ['id' => '244', 'name' => 'New Caledonia', 'continent_id' => '4', 'code' => 'NC', 'timezone' => '+2:00'],
          ['id' => '245', 'name' => 'New Zealand', 'continent_id' => '4', 'code' => 'NZ', 'timezone' => '+2:00'],
          ['id' => '246', 'name' => 'Niue', 'continent_id' => '4', 'code' => 'NU', 'timezone' => '+2:00'],
          ['id' => '247', 'name' => 'Norfolk Island', 'continent_id' => '4', 'code' => 'NF', 'timezone' => '+2:00'],
          ['id' => '248', 'name' => 'Northern Mariana Islands', 'continent_id' => '4', 'code' => 'MP', 'timezone' => '+2:00'],
          ['id' => '249', 'name' => 'Palau', 'continent_id' => '4', 'code' => 'PW', 'timezone' => '+2:00'],
          ['id' => '250', 'name' => 'Papua New Guinea', 'continent_id' => '4', 'code' => 'PG', 'timezone' => '+2:00'],
          ['id' => '251', 'name' => 'Pitcairn Islands', 'continent_id' => '4', 'code' => 'PN', 'timezone' => '+2:00'],
          ['id' => '252', 'name' => 'Samoa', 'continent_id' => '4', 'code' => 'WS', 'timezone' => '+2:00'],
          ['id' => '253', 'name' => 'Solomon Islands', 'continent_id' => '4', 'code' => 'SB', 'timezone' => '+2:00'],
        ];

        //dump($countries);
        foreach ($countries as $key => $country) {
            DB::table('countries')->insert([
                'id' => $country['id'],
                'name' => $country['name'],
                'continent_id' => $country['continent_id'],
                'code' => $country['code'],
            ]);
        }
    }
}
